name: CI Pipeline to build and test Docker image for Model
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-test-pip:
    name: Train and save model for multiple python versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Create artifacts directory
        run: mkdir -p artifacts/model-version-${{ matrix.python-version }}

      - name: Train and save model
        run: |
          python train.py          
          cp artifacts/model.pkl artifacts/model-version-${{ matrix.python-version }}/model.pkl
          ls -la artifacts/model-version-${{ matrix.python-version }}/model.pkl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-version-${{ matrix.python-version }}.pkl
          path: artifacts/model-version-${{ matrix.python-version }}/model.pkl

      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .  
          push: false
          tags: user/mlops-model:python-${{ matrix.python-version }}
          file: Padmaja_ML_OPS_Implementation/Dockerfile